---
- name: Check for online hosts
  hosts: all
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: ios

  tasks:
    - name: Ping for reachability
      command: ping -c3 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: true
      check_mode: False

    - name: Group hosts by online
      group_by: key=reachable
      when: ping_result.rc == 0
      check_mode: False

- name: Check and set cisco compliance configuration items
  hosts: reachable
  gather_facts: False
  connection: network_cli
  vars:
    ansible_network_os: ios
  include_vars:
    vars: vars/vars.yml
  collections:
    - cisco.ios

  tasks:
    - name: Gather device information
      cisco.ios.ios_facts:

    - name: Generate template when 3560 switch
      cisco.ios.ios_config:
        backup: yes
        src: templates/3560cx_compliance_template.j2
        #Pwhen: ansible_facts.ansible_net_model == 'WS-C3560CX-12PC-S'
  # - name: Save configuration when changes are made
  #   cisco.ios.ios_command:
  #     lines: "write memory"
  #   when: not ansible_check_mode and config_results.changed
